usb: dwc3: imx8mp: fix compiling error
The 'xhci-plat.h' file used to include 'xhci.h', but it was later
removed on commit f78ff8825eb8 ("usb: xhci-plat: Don't include xhci.h").
'dwc3-imx8mp.c' file includes 'core.h', which includes 'xhci-plat.h'.

Because of this change, now 'dwc3-imx8mp.c' does not compile anymore, with
the following error:

drivers/usb/dwc3/dwc3-imx8mp.c:121:19: error: ‘XHCI_MISSING_CAS’ undeclared here (not in a function)
  121 |         .quirks = XHCI_MISSING_CAS |
      |                   ^~~~~~~~~~~~~~~~
drivers/usb/dwc3/dwc3-imx8mp.c:122:19: error: ‘XHCI_SKIP_PHY_INIT’ undeclared here (not in a function)
  122 |                   XHCI_SKIP_PHY_INIT,
      |                   ^~~~~~~~~~~~~~~~~~

Fix this by including the correct header files.

Signed-off-by: Hiago De Franco <hiago.franco@toradex.com>