drm: of: Fix build without CONFIG_OF
Fix the following build error when CONFIG_OF is not enabled

```
In file included from drivers/gpu/drm/drm_bridge.c:34:
./include/drm/drm_of.h:87:12: error: ‘drm_of_component_probe_with_match’ defined but not used [-Werror=unused-function]
   87 | static int drm_of_component_probe_with_match(struct device *dev,
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

drm_of_component_probe_with_match() must be declared as inline likewise
all the other functions in the same header are.

Fixes: dcc7dc895c2b ("MLK-16290 drm: Add drm_of_component_probe_with_match() helper")
Signed-off-by: Francesco Dolcini <francesco.dolcini@toradex.com>