net: tsn: fix too many arguments on genlmsg_multicast_allns function
After the merge of v5.15.170, commit 03ca631 ("genetlink: hold RCU
in genlmsg_mcast()") was introduced and it reduces the amount of
arguments from the genlmsg_multicast_allns function, causing the last
argument to be useless. Therefore remove it and fix the following
compilation error:

net/tsn/genl_tsn.c: In function ‘tsn_multicast_to_user’:
net/tsn/genl_tsn.c:3651:15: error: too many arguments to function ‘genlmsg_multicast_allns’
 3651 |         res = genlmsg_multicast_allns(&tsn_family, skb, 0,
      |               ^~~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Hiago De Franco <hiago.franco@toradex.com>