media: nxp: imx8-isi: Fix build error in mxc_isi_m2m_resume()
The conversion to drop the unused argument to mxc_isi_channel_chain()
missed updating one call in mxc_isi_m2m_resume(), causing a build
failure:

drivers/media/platform/nxp/imx8-isi/imx8-isi-m2m.c:736:17: error: too many arguments to function ‘mxc_isi_channel_chain’
  736 |                 mxc_isi_channel_chain(pipe, false);
      |                 ^~~~~~~~~~~~~~~~~~~~~
In file included from drivers/media/platform/nxp/imx8-isi/imx8-isi-m2m.c:35:
drivers/media/platform/nxp/imx8-isi/imx8-isi-core.h:385:5: note: declared here
  385 | int mxc_isi_channel_chain(struct mxc_isi_pipe *pipe);

Remove the unused argument to fix the build.

Fixes: 211728b9b282 ("media: nxp: imx8-isi: Drop unused argument to mxc_isi_channel_chain()")
Signed-off-by: Vitor Soares <vitor.soares@toradex.com>